apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-01-st
spec:
  serviceName: mysql-01-svc
  selector:
    matchLabels:
      app: mysql-01-statefulset
  template:
    metadata:
      name: mysql-01-pod
      labels:
        app: mysql-01-statefulset
    spec:
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /home/mysql/data
      containers:
      - name: container-mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123"
        - name: MYSQL_PASSWORD
          value: "password123"
        - name: MYSQL_DATABASE
          value: "news_aggregator"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql