apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
spec:
  template:
    spec:
      containers:
        - name: migrator-php
          image: ntimdotdev/laravel-news-aggregator-php:0.0.4
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: app-secret
      restartPolicy: Never
  backoffLimit: 1