apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  APP_NAME: "NewsAggregator"
  APP_KEY: "base64:OmeNQb93Sjgj2EohGa/wzWYW78zfzbrg4Qe7JOzGvAY="
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: ""
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  PHP_CLI_SERVER_WORKERS: "4"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stderr"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-01-svc.default"
  DB_PORT: "3306"
  DB_DATABASE: "news_aggregator"
  DB_USERNAME: "root"
  DB_PASSWORD: "password123"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "database"
  CACHE_PREFIX: ""
  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis-01-svc.default"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  NEWS_RETRIEVAL_INTERVAL_MINUTES: "1440"
  NEWSAPI_APIKEY: "81d75655bcba47e791b26988cffc24de"
  NEWSAPI_ENDPOINT: "https://newsapi.org/v2/everything"
  GUARDIANAPI_APIKEY: "f444c18a-1d6e-4dd1-a235-72f535209ce7"
  GUARDIANAPI_ENDPOINT: "https://content.guardianapis.com/search"
  NEWYORKTIMES_APIKEY: "DAYGS3gqbd6YIXOGc50nQXOXZS6w3Wnq"
  NEWYORKTIMES_ENDPOINT: "https://api.nytimes.com/svc/search/v2/articlesearch.json"